# Generated by Django 4.2.23 on 2025-07-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kisibilgisi',
            name='kategori',
            field=models.CharField(choices=[('Aile', 'Aile'), ('İş', 'İş'), ('Acil', 'Acil'), ('Diğer', 'Diğer')], default='Diğer', max_length=10),
        ),
        migrations.AlterField(
            model_name='kisibilgisi',
            name='telefon',
            field=models.CharField(max_length=11),
        ),
    ]
