# Generated by Django 4.2.23 on 2025-07-27 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kullanici', '0003_kullanicilog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanicilog',
            name='tarih_saat',
        ),
        migrations.AddField(
            model_name='kullanicilog',
            name='zaman',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kullanicilog',
            name='islem',
            field=models.CharField(max_length=255),
        ),
    ]
