# Generated by Django 4.2.23 on 2025-07-27 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kullanici', '0005_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='alici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alinanlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='gonderen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilenler', to=settings.AUTH_USER_MODEL),
        ),
    ]
